#!/bin/bash

# script to retrieve bbc radio stations 
# and store them into an mpd playlist

# bbc 3
curl http://www.bbc.co.uk/radio/listen/live/r3_aaclca.pls | grep File | cut -d "=" -f2-6 > ~/.mpd/playlists/bbcradio3.m3u

# bbc 4
curl http://www.bbc.co.uk/radio/listen/live/r4_aaclca.pls | grep File | cut -d "=" -f2-6 > ~/.mpd/playlists/bbcradio4.m3u
