#!/bin/sh
#
# check_updates.sh
#
# CREATED:  2008-11-03 13:32
# MODIFIED: 2010-11-10 12:29
#
ignore=$(sed -rn '/^\s*IgnorePkg/{s/.*=\s*//; s/\s+/|/gp}' /etc/pacman.conf)
updates=$(pacman -Qqu | grep -Ev "^($ignore)$" | wc -l)

[ $updates -gt 0 ] && echo -n "^fg(grey25)^i(/home/zeke/.icons/xbm8x8/pacman.xbm)^fg(grey60)  $updates update"
[ $updates -gt 1 ] && echo "s" || exit 0
