#!/bin/bash

cache=~/.cache/dmenu

regen_cache() {
  find "${paths[@]}" -maxdepth 1 \( -type f -o -type l \) -executable -printf '%f\n' |
      sort -u >"$cache"
}


getbins() {
  IFS=':' read -r -a paths <<< "$PATH"
  for path in "${paths[@]}"; do
    if [[ $path -nt $cache ]]; then
      regen_cache
      break
    fi
  done
  cat "$cache"
}

cmd=$(getbins | dmenu ${DMENU_OPTIONS:--i})

# dispatch!
case $cmd in
  ncmpcpp|htop|vim)   exec $term -name $cmd -e $cmd ;;
  *)                  exec $cmd
esac

