#!/bin/bash
#
# leave - pbrisbin 2011
#
# a simple shut-down dialog implemented via dmenu
# 
# note: requires NOPASWD entries for the commands involved
#
# todo:
#       verify bash version supports assoc arrays
#
###

errorout() { echo "error: $*"                 ; exit 1; }
message()  { echo 'usage: leave [ --no-sudo ]'; exit 1; }

have() { which $1 &>/dev/null; }

[[ "$1" =~ -h|--help ]] && message

declare -A choices

choices[logout]='systemctl --user exit'
choices[shutdown]='systemctl poweroff'
choices[reboot]='systemctl reboot'
choices[suspend]='systemctl suspend'

dmenu="dmenu ${DMENU_OPTIONS:--i}"

choice="$(printf "%s\n" "${!choices[@]}" | $dmenu)" 

if [[ -n "$choice" ]]; then
  action="${choices[$choice]}"
  [[ -n "$action" ]] && $action
fi
