#!/bin/sh
#
# ~/.bin/mailcount script to display new email in conky(dzen)
# Kevin Casucci 2012
#

maildirs="$HOME/Mail/*/INBOX/new/"
mail="$(find $maildirs -type f | wc -l)"

[ $mail -gt 0 ] && echo -n "^fg(grey25)^i(/home/zeke/.icons/xbm8x8/mail.xbm)^fg(grey60) $mail letter"
[ $mail -gt 1 ] && echo "s" || exit 0
