#!/bin/bash
#
# filename: pavol
# Usage:
#      pavol <--increase/--decrease/--toggle-mute>
# 
#
#Customize this stuff
SECS="1"            # sleep $SECS
BG="#303030"        # background colour of window
FG="#606060"        # foreground colour of text/icon
BAR_FG="#60b48a"    # foreground colour of volume bar
BAR_BG="#606060"    # background colour of volume bar
HEIGHT="50"         # window height
WIDTH="400"         # window width
BAR_WIDTH="300"     # width of volume bar
ICON=~/.pulse/dzen_icons/vol-hi.xbm
FONT="-*-terminus-medium-r-*-*-14-*-*-*-*-*-*-*"
PULSE_MAX_VOL=100

# No need to customize this variable
PIPE="/tmp/pulsevolpipe"

# Lets find the appropriate positioning for the volume bar
XRES=`xdpyinfo|grep 'dimensions:'|awk '{print $2}'|cut -dx -f1`
XPOS=$[$XRES / 2 - $WIDTH / 2]          # horizontal positioning
YRES=`xdpyinfo|grep 'dimensions:'|awk '{print $2}'|cut -dx -f2`
YPOS=$[$YRES * 4 / 5]                   # vertical positioning

# Sets the desired volume
function set_volume()
{
  CURVOL=$1
  ponymix set-volume $CURVOL
}

# Gets the current volume
function get_volume()
{
    MIXER=$(ponymix get-volume)
    echo $MIXER
}

# Get muted ? returns boolean
function get_muted()
{
    MUTED=$(ponymix is-muted)
    echo $MUTED
}

VOL=$(get_volume)
CURVOL=$[$VOL]
MUTE=$(get_muted)         # Reads mute state

if [[ $1 == "--increase" ]]
then
    CURVOL=$(($CURVOL + 5))
    if [[ $CURVOL -ge $PULSE_MAX_VOL ]]
    then
        CURVOL=$PULSE_MAX_VOL
    fi
    set_volume $CURVOL
elif [[ $1 == "--decrease" ]]
then
    CURVOL=$(($CURVOL - 5))
    if [[ $CURVOL -le 0 ]]
    then
        CURVOL=0
    fi
    set_volume $CURVOL
elif [[ $1 == "--toggle-mute" ]]
then
    if [[ $MUTED ]]
    then
        ponymix unmute
    else
        ponymix toggle
        CURVOL=0
    fi
fi

# showing in dzen2
if [ ! -e "$PIPE" ];
# if pipe file does not exist
then
  mkfifo "$PIPE"
  (dzen2 -tw "$WIDTH" -h "$HEIGHT" -x "$XPOS" -y "$YPOS" -fn "$FONT" -bg "$BG" -fg "$FG" < "$PIPE" 
  rm  -f "$PIPE") &
fi

# feed the pipe
(echo $[$CURVOL]| gdbar -l "^i($ICON)" -fg "$BAR_FG" -bg "$BAR_BG" -w "$BAR_WIDTH"  ; sleep "$SECS" ) > "$PIPE"
