#!/bin/bash

fakedb=/dev/shm/fakepacdb

pkgs=$(pacman --dbpath "$fakedb" -Qqu | wc -l)
aurpkgs=$(cower -udf 2> /dev/null | wc -l)
ICON="$HOME/.icons/pacman.png"

unset msg1
unset msg2
unset packages

if [[ ${pkgs} -gt 0 ]]; then
    msg1=" ${pkgs} in pacman "
fi 

if [[ ${aurpkgs} -gt 0 ]]; then
    msg2=" ${aurpkgs} in AUR "
fi 

let packages=${pkgs}+${aurpkgs}
if [[ ${packages} -gt 0 ]]; then
    notify-send -i "${ICON}" --expire-time=10000 "There are ${packages} out of date packages (${msg1}${msg2})"
fi
