#!/bin/bash

fakedb=/dev/shm/fakepacdb

pkgs=$(pacman --dbpath "$fakedb" -Qqu | wc -l)
aurpkgs=$(aurget -Su 2> /dev/null | wc -l)

unset msg1
unset msg2
unset packages

if [[ ${pkgs} -gt 0 ]]; then
    msg1=" ${pkgs} in pacman "
fi 

if [[ ${aurpkgs} -gt 0 ]]; then
    msg2=" ${aurpkgs} in AUR "
fi 

let packages=${pkgs}+${aurpkgs}
if [[ ${packages} -gt 0 ]]; then
    xmessage -title "Package Updates" -timeout 20 -center "There are ${packages} out of date packages (${msg1}${msg2})"
fi
